//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropBoxApplication.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class addressmaster
    {
        public int AddressId { get; set; }
        public string CompleteAddress { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string ZipCode { get; set; }
        public string LandMark { get; set; }
        public Nullable<int> LoginID { get; set; }
        public string PhoneNumber { get; set; }
    }
}
