//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropBoxApplication.DBHelper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class evergreen_androidEntities : DbContext
    {
        public evergreen_androidEntities()
            : base("name=evergreen_androidEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<addressmaster> addressmasters { get; set; }
        public virtual DbSet<categorymaster> categorymasters { get; set; }
        public virtual DbSet<citymaster> citymasters { get; set; }
        public virtual DbSet<localitymaster> localitymasters { get; set; }
        public virtual DbSet<notificationmaster> notificationmasters { get; set; }
        public virtual DbSet<orderdetail> orderdetails { get; set; }
        public virtual DbSet<ordermaster> ordermasters { get; set; }
        public virtual DbSet<orderstatusmaster> orderstatusmasters { get; set; }
        public virtual DbSet<productmaster> productmasters { get; set; }
        public virtual DbSet<promocodemaster> promocodemasters { get; set; }
        public virtual DbSet<registrationmaster> registrationmasters { get; set; }
        public virtual DbSet<statemaster> statemasters { get; set; }
        public virtual DbSet<storemaster> storemasters { get; set; }
        public virtual DbSet<usermaster> usermasters { get; set; }
        public virtual DbSet<website_login> website_login { get; set; }
    }
}
