//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropBoxApplication.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class promocodemaster
    {
        public int PromoCodeId { get; set; }
        public string PromoCode { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> LoginId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
