//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropBoxApplication.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class registrationmaster
    {
        public int LoginID { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> Role { get; set; }
        public string OTP { get; set; }
        public string ProfilePictureURL { get; set; }
        public Nullable<int> FavouriteStoreId { get; set; }
        public string FbToken { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
