//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropBoxApplication.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class website_login
    {
        public int UserId { get; set; }
        public string FisrtName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
